[package]
name = "grip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.0"
clap = "4.4.11"
walkdir = "2.2.3"
rayon = "1.5.2"
memmap = "0.7.0"